version: '3.8'

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: global_db
      POSTGRES_USER: developer
      POSTGRES_PASSWORD: global22!
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build: ./backend
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: postgresql://developer:global22!@db:5432/global_db
    depends_on:
      - db

volumes:
  postgres_data:
